### ISSUE TITLE
Missing some extensions when using SetTypeFilters()

### ISSUE THREAD

**Issue by moso31** [AirGuanZ/imgui-filebrowser#28]
When I try to use SetTypeFilters() like this
```C++
    fileDialog.SetTypeFilters({ ".*", ".dds" });
```

And make filter combobox to ",*". Then I'll get this
![image](https://user-images.githubusercontent.com/15684115/108591443-c6f8f500-73a3-11eb-9589-ed2f2f926548.png)

But I think it should be
![image](https://user-images.githubusercontent.com/15684115/108591470-eb54d180-73a3-11eb-8b24-65b328cc147f.png)
(2 hdr file missed.)

So I switched location of these two code segments
```C++
    // all type filters
    if(typeFilters_.size() > 1 && typeFilterIndex_ == 0)
    {
        for(size_t i = 1; i < typeFilters_.size(); ++i)
        {
            if(extension == typeFilters_[i])
                return true;
        }
        return false;
    }

    // universal filter
    if(typeFilters_[typeFilterIndex_] == std::string_view(".*"))
        return true;
```

to 

```C++
    // universal filter
    if(typeFilters_[typeFilterIndex_] == std::string_view(".*"))
        return true;

    // all type filters
    if(typeFilters_.size() > 1 && typeFilterIndex_ == 0)
    {
        for(size_t i = 1; i < typeFilters_.size(); ++i)
        {
            if(extension == typeFilters_[i])
                return true;
        }
        return false;
    }
```

And it will be fixed...
![image](https://user-images.githubusercontent.com/15684115/108591800-784c5a80-73a5-11eb-822e-516afca40e8f.png)

It's good for me. But I'm not sure will this cause any other problems...

**Comment by AirGuanZ** [comment]
Hi,

Thanks for telling me this!

This problem is actually caused by the ` if(typeFilters_.size() > 1 && typeFilterIndex_ == 0)` condition. I used `typeFilters_.size() > 1` to decide whether there is a 'all filter', which may cause incorrect result when there is a '.*'. I've upload a new version, which use a separate member variable to indicate the existence of 'all filter'.

Please try the new version. Hope that works well for you.

**Comment by moso31** [comment]
I've tried the new version and it worked great!
