### ISSUE TITLE
uncaught filesystem error exceptions cause problems

### ISSUE THREAD

**Issue by claudeha** [AirGuanZ/imgui-filebrowser#52]
Hi, thanks for all the good work!

I'm trying to use latest imgui-filebrowser with latest imgui (not docking) with SDL2 2.30.3 on Android 7 Nougat (minTarget API level 21 (Android 5 Lollipop), compileSdk API level 31 (Android 12) with NDK version 25.2.9519653.

But my app crashes when the file browser object is constructed, with an uncaught exception:

```
terminating with uncaught exception of type "std::__ndk1::__fs::filesystem::filesystem_error": filesystem error: in posix_stat: failed to determine attributes for the specified path: Permission denied [/charger]
```

After catching and logging the exceptions, it no longer crashes, but neither do I have working file browsers.

I think it would be best if imgui-filebrowser is robust to filesystem errors so permission issues don't break everything.

Thoughts?

**Comment by AirGuanZ** [comment]
The file browser will initially display the working directory, std::filesystem::current_path(), and will always fall back to that directory if an error occurs. If an error happens again during the fallback process, an uncaught exception will be thrown, as you have encountered.

I will improve the exception handling to be more precise. For example, if the error `failed to determine attributes for the specified path` occurs, the specific directory will be ignored instead of causing the entire directory scan to fail.

On the other hand, what about adding an optional argument `fallbackDirectory` to the constructor to override the default choice?

**Comment by AirGuanZ** [comment]
I have added a new constructor flag `ImGuiFileBrowserFlags_SkipItemsCausingError`. Please try the new version.

**Comment by claudeha** [comment]
Thanks for the quick work!  This looks like a good addition.

Now I get a different filesystem error exception:

```
05-30 18:28:48.179 32319 32346 W SDL/APP : creating file browsers: filesystem error: in directory_iterator::directory_iterator(...): Permission denied [/]
```

I will try to change the current working directory of my program on application startup, if that fails then adding a start directory option might be necessary.

**Comment by AirGuanZ** [comment]
The default directory is now customizable. You can specify a custom default directory by using the optional defaultDirectory argument in the constructor.

**Comment by claudeha** [comment]
thanks! I already added cwd switch to my program and got it working but the new constructor will be useful
