### ISSUE TITLE
Can't dock the window

### ISSUE THREAD

**Issue by AaronFrans** [AirGuanZ/imgui-filebrowser#53]
When the window is opened, it seems that it's not dockable with the ImGui docking

**Comment by AirGuanZ** [comment]
Hi,

That's currently expected since the file browser uses a popup window, which cannot be docked. I can add a 'NoPopup' flag to make it use a regular window, but more problems arise, such as whether a docked window should be closed when the user clicks 'OK'.

Check out the `dockable` branch to try the `ImGuiFileBrowserFlags_NoPopup` option. Any suggestions or pull requests are welcome.

**Comment by AaronFrans** [comment]
Thanks, on first try it seems to be working, I'm going to play around with it for a bit and see if I can come up with a good way to handle the OK/Cancel buttons. I might remove them if it's not a popup since I want to use the browser to monitor my files at runtime, kind of like how unity does its asset browser

**Comment by AirGuanZ** [comment]
I'll close this issue since it has been inactive for a long time. Feel free to reopen it if needed.
